### PR TITLE
qemu: Bump qemu bbappend version to 4.

### PR DESCRIPTION
**Pull request by shruthi-ravi**
Signed-off-by: Shruthi Ravichandran <shruthi.ravichandran@ni.com>

### CODE REVIEW

**Review by amstewart — COMMENTED** [review]
Is this something we need to upstream to meta-ivi for dunfell compatibility?

**Comment by shruthi-ravi** [comment]
I think? The version is still at 3 in upstream [master](http://git.yoctoproject.org/cgit/cgit.cgi/meta-ivi/tree/meta-ivi/recipes-devtools/qemu?h=master). Which branch is this based off of? I don't see a branch cut for dunfell.

**Comment by amstewart** [comment]
GENIVI didn't have a dunfell stable ref when I branched from it back in June; and I suppose they still don't. We should start a dialogue with them about getting a stable branch, as part of your PR.

**Review by amstewart — APPROVED** [review]

**Comment by shruthi-ravi** [comment]
@amstewart merging this change since you mentioned that you will be following up with GENIVI about a stable dunfell branch.

**Pull request merged**
